### ISSUE TITLE
Issues with the Uefi downgrade

### ISSUE THREAD

**Issue by SprSpl** [jlempen/Surface-IceLake-Hibernation-Fix#1]
Using Ubuntu to downgrade my Uefi for the surface laptop 3 but I am encountering multiple issues.
First of all there is no deamon file in the fwupd folder
Second of all when I was trying linux mint to do this the repack script refused to work no matter what.
Third of all now that I switched to Ubuntu I cannot open the msi file using msiextract.
Any help would he greatly appreciated

**Comment by jlempen** [comment]
Hi @SprSpl 
Have a look at [my repository for the Surface Laptop 3](https://github.com/jlempen/Surface-Laptop-3-OpenCore). It contains detailed instructions for setting up macOS on the SL3, including a very straightforward section on how to downgrade the UEFI: https://github.com/jlempen/Surface-Laptop-3-OpenCore?tab=readme-ov-file#downgrading-the-uefi-firmware
This should make it much easier now, as you don't need to download the whole firmware update from Micro$oft and an exctraction script anymore. Just download the firmware files for the SL3 from my repo and use the fwupd tool included in your Linux distro to install the UEFI firmware.

**Comment by SprSpl** [comment]
I tried it however when I paste in thr command you provided it returns
"Error reading from file descriptor: Is a directory"
This is my first time in Linux so I don't really know what this means

**Comment by SprSpl** [comment]
I tried it however when I paste in thr command you provided it returns
"Error reading from file descriptor: Is a directory"
This is my first time in Linux so I don't really know what this means Hi @SprSpl 
> Have a look at [my repository for the Surface Laptop 3](https://github.com/jlempen/Surface-Laptop-3-OpenCore). It contains detailed instructions for setting up macOS on the SL3, including a very straightforward section on how to downgrade the UEFI: https://github.com/jlempen/Surface-Laptop-3-OpenCore?tab=readme-ov-file#downgrading-the-uefi-firmware
> This should make it much easier now, as you don't need to download the whole firmware update from Micro$oft and an exctraction script anymore. Just download the firmware files for the SL3 from my repo and use the fwupd tool included in your Linux distro to install the UEFI firmware.

**Comment by SprSpl** [comment]
> Hi @SprSpl 
> Have a look at [my repository for the Surface Laptop 3](https://github.com/jlempen/Surface-Laptop-3-OpenCore). It contains detailed instructions for setting up macOS on the SL3, including a very straightforward section on how to downgrade the UEFI: https://github.com/jlempen/Surface-Laptop-3-OpenCore?tab=readme-ov-file#downgrading-the-uefi-firmware
> This should make it much easier now, as you don't need to download the whole firmware update from Micro$oft and an exctraction script anymore. Just download the firmware files for the SL3 from my repo and use the fwupd tool included in your Linux distro to install the UEFI firmware.
Hi,thank you for replying.While that worked I now have a new issue,I replaced the Bigsurface kext with the 6.2 one however after rebooting the touchscreen,keyboard and trackpad stopped working.If you know why that is I'd really appreciate some help.

**Comment by SprSpl** [comment]
Hi,thank you for replying.While that worked I now have a new issue,I replaced the Bigsurface kext with the 6.2 one however after rebooting the touchscreen,keyboard and trackpad stopped working.If you know why that is I'd really appreciate some help.
> Hi @SprSpl 
> Have a look at [my repository for the Surface Laptop 3](https://github.com/jlempen/Surface-Laptop-3-OpenCore). It contains detailed instructions for setting up macOS on the SL3, including a very straightforward section on how to downgrade the UEFI: https://github.com/jlempen/Surface-Laptop-3-OpenCore?tab=readme-ov-file#downgrading-the-uefi-firmware
> This should make it much easier now, as you don't need to download the whole firmware update from Micro$oft and an exctraction script anymore. Just download the firmware files for the SL3 from my repo and use the fwupd tool included in your Linux distro to install the UEFI firmware.

**Comment by jlempen** [comment]
BigSurface 6.2 and 6.5 use different kexts and their order in config.plist is different:

BigSurface 6.5
![image](https://github.com/user-attachments/assets/305830d7-7d65-4998-ac2f-af50307f14a3)

BigSurface 6.2
![image](https://github.com/user-attachments/assets/97ded568-5a6b-4ae5-8a20-40afb90798f8)

Seriously, just use the EFI from [my repository for the Surface Laptop 3](https://github.com/jlempen/Surface-Laptop-3-OpenCore), which works very nicely on the 15-Inch as well as the 13-Inch SL3.

**Comment by SprSpl** [comment]
Hi thanks for your reply.Everything seems to work well now.However there's 2 things which I just want to know whether they are common or it'd just a me issue.First one is like 50% of thr time when booting up from sleep the screen turns completely blue for like 10 seconds before actually turning on.And second,every time the laptop turns on from sleep the speakers make a hissing noise however whenever I actually play a sound they do a loud pop noise and the speakers stop with the hiss.These aren't major issues but I would just like to know whether they are common or not.
> BigSurface 6.2 and 6.5 use different kexts and their order in config.plist is different:
> 
> BigSurface 6.5
> ![image](https://github.com/user-attachments/assets/305830d7-7d65-4998-ac2f-af50307f14a3)
> 
> BigSurface 6.2
> ![image](https://github.com/user-attachments/assets/97ded568-5a6b-4ae5-8a20-40afb90798f8)
> 
> Seriously, just use the EFI from [my repository for the Surface Laptop 3](https://github.com/jlempen/Surface-Laptop-3-OpenCore), which works very nicely on the 15-Inch as well as the 13-Inch SL3.

**Comment by jlempen** [comment]
> when booting up from sleep the screen turns completely blue for like 10 seconds

This seems to be normal, the color is not always blue, sometimes it's only white noise or something like a "negative" of the desktop before the SL3 went to sleep... I have this too. No clue how to fix it, though :-)

> every time the laptop turns on from sleep the speakers make a hissing noise however whenever I actually play a sound they do a loud pop noise and the speakers stop with the hiss

This is normal too, it happens on all Surface devices (apart from the Surface Go 2) running macOS. It's because there's only a single ALC layout-ID for all Surface devices in the [AppleALC](https://github.com/acidanthera/AppleALC) repo and unfortunately it has this bug. It should be possible to fix it, but most pretty much normal human beings like myself are absolutely unable to understand AppleALC source code, let alone fix a buggy codecs... Feel free to have a look at it, it's not for the faint of heart :-)

Here's the basics: https://github.com/acidanthera/AppleALC/wiki/Adding-codec-support

And here's the harder stuff: https://github.com/5T33Z0/AppleALC-Guides

**Comment by SprSpl** [comment]
Oh okay thank you.Im happy to just leave these things as is since it's really not a big issue for me so thanks for the assurance they are normal bugs :)
> > when booting up from sleep the screen turns completely blue for like 10 seconds
> 
> This seems to be normal, the color is not always blue, sometimes it's only white noise or something like a "negative" of the desktop before the SL3 went to sleep... I have this too. No clue how to fix it, though :-)
> 
> > every time the laptop turns on from sleep the speakers make a hissing noise however whenever I actually play a sound they do a loud pop noise and the speakers stop with the hiss
> 
> This is normal too, it happens on all Surface devices (apart from the Surface Go 2) running macOS. It's because there's only a single ALC layout-ID for all Surface devices in the [AppleALC](https://github.com/acidanthera/AppleALC) repo and unfortunately it has this bug. It should be possible to fix it, but most pretty much normal human beings like myself are absolutely unable to understand AppleALC source code, let alone fix a buggy codecs... Feel free to have a look at it, it's not for the faint of heart :-)
> 
> Here's the basics: https://github.com/acidanthera/AppleALC/wiki/Adding-codec-support
> 
> And here's the harder stuff: https://github.com/5T33Z0/AppleALC-Guides
